### ISSUE TITLE
Créer l’arborescence du projet Express

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#1]
- [x] Définir si on a besoin de tout ce qui est créé par défaut par `express-generator` => visiblement non (pas de vues, …)
- [x] Si non, définir de quels outils on a besoin (routage de base ? évoulé ?)
- [x] Définir une arborescence propre

**Comment by Aliciahan** [comment]
## MEAN Stack (MongoDB, Express, AngularJS, Node.js)

Est-ce qu'on utilise 

``` bash
npm install -g express-generator
express -ejs(ou d'autres plugin de VIEWS) <Nom du projet>
```

j'ai commence un peu de decouvrir ce Stack, et je trouve qu'il me semble: 
    il y a bcp d'outils qui peut faire la meme choses particulierement pour la partie - Views. Donc je vous liste un peu des problemes dans ma tete pour l'instant...

### Question :

---
- Quel moteur de Views qu'on utilise? (choix entre jade, handlebars, ejs, etc.) 
- Quel version Angular on s'emplois? On the telecharge ou on utilise CDN?
- Version BootStrap?
- Repertoire /public/<- standaliser l'appelations des sous-repertoires ici pour qu'on peut acceder aux ressources.

**Comment by ejpcmac** [comment]
Je crois que pour l’instant la partie vue n’est pas une urgence puisqu’elle sera utile uniquement pour l’interface d’administration — notre client de démonstration va être ultra-basique pour le moment. On aura l’occasion d’en rediscuter cette semaine.

En ce qui concerne l’arborescence de la partie serveur, il faut voir si `express-generator` est vraiment utile. J’ai vu qu’il génère pas mal de choses, mais pour un service web tout n’est peut-être pas nécessaire. Je vais étudier ça aujourd’hui ou mardi, je n’ai pas eu le temps de le faire ce week-end. J’en ai profité pour regarder un peu MongoDB et rédiger le CONTRIBUTING.md.

**Comment by Aliciahan** [comment]
je suis d'accord, mais, si on va utiliser angular.JS et un template pour le view, il vaut mieux de décider où qu'on mettre les librairies, des modules, des routes etc... cela va nous permet de réduire le travail du fusion pour la suite. 

Pour l'instant, je suis entrain de rattraper une connaissance sur comment les choses marche ensemble, et quelle partie s'occupe de quoi, etc.... je suis pas sûr j'ai tout à faire compris, de toute façon on va en parler la semaine prochaine, bon fin weekend à tous

**Comment by ejpcmac** [comment]
> je suis d'accord, mais, si on va utiliser angular.JS et un template pour le view, il vaut mieux de décider où qu'on mettre les librairies, des modules, des routes etc... cela va nous permet de réduire le travail du fusion pour la suite.

À mon avis il faut que l’interface d’administration soit une application à part entière. Ce sera juste un client particulier qui fera des appels à notre API, donc son développement aura lieu dans un autre repos.
