### ISSUE TITLE
Requête getPictures

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#12]
Implémenter la requête `getPictures` permettant de récupérer les images d’un lieu [telle que décrite dans la documentation](https://github.com/participamap/participamap/blob/master/documentation/API.md#images-dun-lieu).
### Note pour les champs `author`

Ces champs représentent un utilisateur et sont enregistrés dans la base de données comme un `ObjectId`. Pour éviter au client d’avoir à faire des requêtes API supplémentaires, ils doivent être remplacés par un objet défini de la manière suivante :
- **id:** ObjectId
- **name:** String

où `id` garde la valeur du champ d’origine et `name` contient le nom complet de l’utilisateur.

Ce remplacement ayant lieu aussi dans d’autres appels API, il doit être réalisé par une fonction dédiée et cette fonction appelée par les appels retournant ces champs.

**Comment by Aliciahan** [comment]
Il me semble sauvegarder dans Amazon S3 et enregistrer un String address dans le mongodb est une façon réalisable. Mais je sais rien pour l'instant .... à découvrir ...

**Comment by ejpcmac** [comment]
Même un serveur à nous dans un premier temps pour la phase de développement, ça peut marcher. On stockera des URL complètes de toute façon, donc pas de soucis sur la cible finale.
