### ISSUE TITLE
Changer les res.send() en res.json()

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#17]
L’appel à `res.send()` est correct, mais au cas où le paramètre n’est pas un objet JSON valide, il vaut mieux appeler `res.json()` qui le transforme en objet JSON valide.

**Comment by StephaneSec** [comment]
Je suis d'accord (au sens j'ai compris) et d'ailleurs c'est ce que m'avait
dit Xicun.
Bon à part ça le mail de JL Lambert me fait dire qu'on a bien géré le
client et c'est plutôt très bien.
Bon week-end

Le 23 sept. 2016 17:50, "Jean-Philippe Cugnet" <notifications@github.com> a
écrit :

**Comment by ejpcmac** [comment]
J’avais noté justement, et j’ai regardé la différence. N’oublie pas que tes réponses sont sur GitHub et donc en public ;)
