### ISSUE TITLE
Sérialiser les commentaires, images et documents et votes d’un lieu

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#29]
Le principe des sous-documents dans MongoDB est très intéressant : il permet à un document de contenir d’autres documents lui étant directement liés. Cela peut être très pratique dans certains cas, notamment si le nombre de sous-documents n’est pas très élevé ou si les données ne sont pas amenées à changer régulièrement.

Toutefois, si un document contient beaucoup de sous-documents ou que :
- le document est amené à être modifié régulièrement ;
- des sous-documents sont ajoutés ou supprimés régulièrement ;

des pertes de performances importantes peuvent avoir lieu, et il devient alors plus rentable de sérialiser les données.

Pour plus d’informations, [cet article d’un blog spécialisé sur MongoDB](http://blog.mlab.com/2013/04/thinking-about-arrays-in-mongodb/) en parle.

La solution serait alors de :
- supprimer les attributs `comments`, `pictures` et `documents` dans l’entité `Place` ;
- créer des entités `Comment`, `Picture`, `Document` et `Vote` avec les modèles existant déjà, auxquels on ajouterait simplement un attribut `place` de type `ObjectId`.

La création et la suppression de ces entités serait alors simplifiée dans le code et en terme de performances. D’un autre côté, la suppression de ces entités lors de la suppression d’un lieu demanderait quelques actions en plus sans toutefois compliquer trop le code.

Avec votre accord je peux me charger de réaliser cette migration qui ne demande pas un travail monstrueux côté code serveur — côté client rien ne change, côté BDD de démonstration il y a toutefois quelques petites modifications à apporter.

P.S. : Doit-on garder la possibilité de récupérer directement une première page de commentaires, images ou documents directement dans le requête `getPlaceInfo` ? S’ils ne sont plus stockés directement dans la `Place`, cela me paraît superflu.

**Comment by StephaneSec** [comment]
Cela semble intéressant mais je crois que :
- les délais sont trop courts.
- nous sommes déjà quelques uns à avoir du mal à toujours être efficace
  avec une structure qui est pourtant désormais familière.
- avec le manque de temps dont nous disposons, nous avons BESOIN que tu
  continues dans l'implémentation des requêtes.

Comme souvent tu dois à mon avis subir nos difficultés techniques mais nous
avons vraiment besoin d'élément stable désormais.

Cela dit c'est mon avis, rien de plus ; )

Le 5 oct. 2016 14:08, "Jean-Philippe Cugnet" notifications@github.com a
écrit :

**Comment by ejpcmac** [comment]
@StephaneSec J’avais déjà commencé à travailler sur la serialisation quand j’ai vu ton message, du coup j’ai fini sur ma lancée et j’ai posté le PR #30, qui sera à discuter demain.

Au final ça ne change pas énormément de choses, si ce n’est améliorer la performance, et surtout simplifier le code, ce qui peut être une aide à la compréhension pour le reste du groupe. D’ailleurs au début intuitivement il me semble que @gwen14123 et @thibolepilote concevaient les commentaires, image, etc. comme des entités à part entières. Un peu content du nouveau jouet qu’était MongoDB et des possibilités assez surprenantes qu’il offrait, j’ai foncé tête baissée sans chercher à fond comment interagir avec les sous-documents, et tu as bien vu en essayant de le faire que c’était assez complexe. Je m’y suis frotté aussi en implémentant `createPicture`.

Après recherche et une nouvelle phase de compréhension de MongoDB, il semble que les sous-documents sont fait pour être manipulés avec l’objet entier (en gros, tu récupère l’objet, tu modifie tes sous-documents, tu enregistres le tout). Du coup c’est génial si tu as peu de sous-documents et qu’ils ont une utilité particulière, mais pour des commentaires, ce n’est pas le bon modèle à utiliser.

Quant à l’implémentation des requêtes, il faut passer à l’authentification. Et vu que @Aliciahan a déjà fait des choses, plutôt que de la conception via la documentation puis de l’implémentation, je pense que le plus efficace va être de voir ce qui est déjà fait, l’intégrer proprement à la branche master, et documenter le tout. (Du coup Xicun il faudra qu’on passe un peu de temps à bosser ensemble demain et vendredi pour intégrer ton travail, c’est primordial)

**Comment by StephaneSec** [comment]
OK, pas de soucis.
Pour en avoir discuter avec Xicun elle trouve ça plutôt pas mal SI ça ne
retarde pas ce qu'on doit faire.
On verra demain.
