### ISSUE TITLE
Requête pour créer un lieu

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#3]
_À définir d’abord dans la documentation._

**Comment by ejpcmac** [comment]
On souhaite créer un lieu sans pour l’instant vérifier les droits d’accès.

* **Requête :** `POST /lieux` avec en charge un lieu

### Lieu

*En italique, attributs optionels*

* Titre
* Liste de points
* *Description*
* *Image*

### Point

* Latitude
* Longitude

**Comment by gwen14123** [comment]
Pour pouvoir développer avec la libraire OpenLayers afn d'avoir accès à OpenStreetMap :
il est important de mettre cette librairie dans le projet !

http://openlayers.org/two/
