### ISSUE TITLE
Création du CollectionDriver

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#4]
Le `CollectionDriver` doit permettre de :
- [ ] Récupérer une collection => `getCollection(collectionName, callback)`
- [ ] Lister l’ensemble des ressources d’une collection => `findAll(collectionName, options, callback)`
- [ ] Récupérer une ressource particulière grâce à son `id` => `get(collectionName, id, callback)`
- [ ] Enregistrer une nouvelle ressource dans une collection => `save(collectionName, obj, callback)`
- [ ] Modifier une ressource grâce à son `id` => update(collectionName, id, obj, callback)`
- [ ] Supprimer une ressource grâce à son `id` => delete(collectionName, id, callback)`

**Comment by Aliciahan** [comment]
https://github.com/theneurasthenicrat/whale4 
http://strokes.imag.fr/whale4
