### ISSUE TITLE
Requête getPlaceInfo

### ISSUE THREAD

**Issue by ejpcmac** [participamap/participamap#7]
Implémenter la requête `getPlaceInfo` permettant de récupérer les informations d’un lieu [telle que décrite dans la documentation](https://github.com/participamap/participamap/blob/master/documentation/API.md#informations-dun-lieu).
### Note pour le paramètre `admin=true`

Dans un premier temps, ne pas vérifier si le client est autorisé à demander `admin=true`. La vérification ne s’effectuera de toute façon pas dans le code de la fonction `getPlaceInfo` mais dans un callback de vérification spécifique qui sera appelé avant cette dernière. On suppose donc que l’utilisateur aura de toute façon le droit d’accéder à la ressource, quels que soient les paramètres.
### Note pour le champ `proposedBy` et les champs `author` des commentaire, images, documents et votes

Ces champs représentent un utilisateur et sont enregistrés dans la base de données comme un `ObjectId`. Pour éviter au client d’avoir à faire des requêtes API supplémentaires, ils doivent être remplacés par un objet défini de la manière suivante :
- **id:** ObjectId
- **name:** String

où `id` garde la valeur du champ d’origine et `name` contient le nom complet de l’utilisateur.

Ce remplacement ayant lieu aussi dans d’autres appels API, il doit être réalisé par une fonction dédiée et cette fonction appelée par les appels retournant ces champs.

**Comment by ejpcmac** [comment]
@DomeProjet Est-ce que je peux bosser dessus ?

**Comment by StephaneSec** [comment]
Je suis avec Gwen, Xicun et Tibaut : c'est OK pour nous. Vas-y

Le 28 sept. 2016 14:23, "Jean-Philippe Cugnet" notifications@github.com a
écrit :

**Comment by DomeProjet** [comment]
@ejpcmac  Desole je regarde ce message trop tard grace a la coupure d'electricite chez moi ce soir
